server:
  port: 8080

  servlett:
    #项目路径
    context-path: /
#连接数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
      #配置Thymeleaf
    thymeleaf:
      cache: false                  #关闭页面缓存
      encoding: UTF-8               #模板编码
      prefix: classpath:/templates/ #页面映射路径
      suffix: .html                 #视图后缀
      model: HTML                   #模板模式
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zz.firstspringboot.entity
  configuration:
    map-underscore-to-camel-case: true
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable:  true
  support-methods-arguments: true
  params: count=countSql
#查看sql语句
logging:
  level:
    com.zz.firstspringboot.mapper: DEBUG
